apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: volwuu2rj-python 
  janus-idp.io/tekton: volwuu2rj-python
  backstage.io/kubernetes-id: volwuu2rj-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: volwuu2rj-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml