apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: volwuu2rj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: volwuu2rj-python 
  name: volwuu2rj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: volwuu2rj-python 
